name: NerdyDragon
version: ${project.version}
author: bermudalocket
main: com.bermudalocket.nerdydragon.NerdyDragon
depend: [EntityMeta]
softdepend: [Multiverse-Core]
api-version: 1.13

permissions:
  nerdydragon.admin:
    description: Full permissions
    default: op

commands:
  nd-fight:
    description: Manage the current dragon fight.
    permission: nerdydragon.admin
    permission-message: You don't have permission to do that!
    usage: |

      §e/<command> butcher§f - Butchers all entities summoned in this fight except the dragon and the crystals.
      §e/<command> butcher-all§f - Butchers all entities summoned in this fight.
      §e/<command> debug§f - Displays information about the current fight.
      §e/<command> skip§f - Skips the current stage of the fight.
      §e/<command> stop§f - Stops the current fight.
  nd-leaderboard:
    description: Displays fight statistics.
    usage: |

      §e/<command> statistics <solo/group>§f - Shows statistics for all solo/group fights.
      §e/<command> top <solo/group> [n = 5]§f - Shows the n fastest solo/group fight times.
  nd-reload:
    description: Reloads the plugins configuration.
    permission: nerdydragon.admin
    permission-message: You don't have permission to do that!
    usage: |

      §e/<command>§f - Reloads the plugin configuration.
  nd-toggle:
    description: Toggles the state (enabled/disabled) of the plugin's actions.
    permission: nerdydragon.admin
    permission-message: You don't have permission to do that!
    usage: |

      §e/<command>§f - Toggles the plugin state.