name: NerdyDragon
version: 1.3
author: bermudalocket
main: com.bermudalocket.nerdydragon.NerdyDragon

permissions:
  nerdydragon.admin:
    description: Full permissions
    default: op

commands:
  nd-add:
    description: Adds the item in the sender's main hand to the dragon loot table.
    usage: /nd-add
    permission: nerdydragon.admin
    permission-message: You don't have permission to do that!
  nd-list:
    description: Lists all of the currently loaded custom drops.
    usage: /nd-list
    permission: nerdydragon.admin
    permission-message: You don't have permission to do that!
  nd-peek:
    description: Gives the command executor one copy of all currently loaded custom drops.
    usage: /nd-peek
    permission: nerdydragon.admin
    permission-message: You don't have permission to do that!
  nd-reload:
    description: Reloads the plugins configuration.
    usage: /nd-reload
    permission: nerdydragon.admin
    permission-message: You don't have permission to do that!
  nd-toggle:
    description: Toggles the state (enabled/disabled) of the plugin's actions.
    usage: /nd-toggle
    permission: nerdydragon.admin
    permission-message: You don't have permission to do that!